################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../CMSIS-DSP/Source/FilteringFunctions/FilteringFunctions.c \
../CMSIS-DSP/Source/FilteringFunctions/FilteringFunctionsF16.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_conv_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q7.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q7.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_conv_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_conv_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_conv_q7.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f16.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f64.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q7.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q7.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f64.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f64.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_f16.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_f64.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f16.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f64.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q7.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_q7.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q7.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_lms_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q31.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_lms_q15.c \
../CMSIS-DSP/Source/FilteringFunctions/arm_lms_q31.c 

OBJS += \
./CMSIS-DSP/Source/FilteringFunctions/FilteringFunctions.o \
./CMSIS-DSP/Source/FilteringFunctions/FilteringFunctionsF16.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q7.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q7.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_q7.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f16.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f64.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q7.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q7.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f64.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f64.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_f16.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_f64.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f16.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f64.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q7.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_q7.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q7.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q31.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_q15.o \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_q31.o 

C_DEPS += \
./CMSIS-DSP/Source/FilteringFunctions/FilteringFunctions.d \
./CMSIS-DSP/Source/FilteringFunctions/FilteringFunctionsF16.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q7.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q7.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_conv_q7.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f16.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f64.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q7.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q7.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f64.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f64.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_f16.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_f64.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f16.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f64.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q7.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_q7.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q7.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q31.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_q15.d \
./CMSIS-DSP/Source/FilteringFunctions/arm_lms_q31.d 


# Each subdirectory must supply rules for building sources it contributes
CMSIS-DSP/Source/FilteringFunctions/%.o CMSIS-DSP/Source/FilteringFunctions/%.su CMSIS-DSP/Source/FilteringFunctions/%.cyclo: ../CMSIS-DSP/Source/FilteringFunctions/%.c CMSIS-DSP/Source/FilteringFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DARM_MATH_CM4 -DUSE_HAL_DRIVER -DSTM32F446xx -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I"C:/FACULTAD/Materias--4to-2do/Procesamiento Digital de Señales/procesamiento_digital_s/develop_stm_board/lab2/CMSIS-DSP/Include" -I"C:/FACULTAD/Materias--4to-2do/Procesamiento Digital de Señales/procesamiento_digital_s/develop_stm_board/lab2/CMSIS-DSP/Include/dsp" -I"C:/FACULTAD/Materias--4to-2do/Procesamiento Digital de Señales/procesamiento_digital_s/develop_stm_board/lab2/CMSIS-DSP/PrivateInclude" -O0 -ffunction-sections -fdata-sections -Wall -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=hard -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-CMSIS-2d-DSP-2f-Source-2f-FilteringFunctions

clean-CMSIS-2d-DSP-2f-Source-2f-FilteringFunctions:
	-$(RM) ./CMSIS-DSP/Source/FilteringFunctions/FilteringFunctions.cyclo ./CMSIS-DSP/Source/FilteringFunctions/FilteringFunctions.d ./CMSIS-DSP/Source/FilteringFunctions/FilteringFunctions.o ./CMSIS-DSP/Source/FilteringFunctions/FilteringFunctions.su ./CMSIS-DSP/Source/FilteringFunctions/FilteringFunctionsF16.cyclo ./CMSIS-DSP/Source/FilteringFunctions/FilteringFunctionsF16.d ./CMSIS-DSP/Source/FilteringFunctions/FilteringFunctionsF16.o ./CMSIS-DSP/Source/FilteringFunctions/FilteringFunctionsF16.su ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.d ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.o ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.su ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.d ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.o ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.su ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.d ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.o ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.su ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.d ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.o ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.su ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.d ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.o ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.su ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.d ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.su ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.d ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.o ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.su
	-$(RM) ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.d ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.o ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.su ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q7.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q7.d ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q7.o ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q7.su ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.d ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.o ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.su ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q7.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q7.d ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q7.o ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q7.su ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_q7.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_q7.d ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_q7.o ./CMSIS-DSP/Source/FilteringFunctions/arm_conv_q7.su ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f16.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f16.d ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f16.o ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f16.su ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f64.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f64.d
	-$(RM) ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f64.o ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f64.su ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q7.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q7.d ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q7.o ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q7.su ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q7.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q7.d ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q7.o ./CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q7.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f64.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f64.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f64.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f64.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f64.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f64.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f64.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f64.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_f16.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_f16.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_f16.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_f16.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_f64.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_f64.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_f64.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_f64.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f16.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f16.d
	-$(RM) ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f16.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f16.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f64.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f64.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f64.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f64.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q7.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q7.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q7.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q7.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_q7.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_q7.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_q7.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_q7.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.d
	-$(RM) ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q7.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q7.d ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q7.o ./CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q7.su ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.d ./CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.o ./CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.su ./CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.d ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.o ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.su ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q15.o ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q31.su ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_q15.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_q15.d ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_q15.o
	-$(RM) ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_q15.su ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_q31.cyclo ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_q31.d ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_q31.o ./CMSIS-DSP/Source/FilteringFunctions/arm_lms_q31.su

.PHONY: clean-CMSIS-2d-DSP-2f-Source-2f-FilteringFunctions

